# figure out
set(VERSION ${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_MICRO}.${VERSION_PATCH})
exec_program(${HYPERTABLE_SOURCE_DIR}/bin/src-utils/ver ${HYPERTABLE_SOURCE_DIR}
             OUTPUT_VARIABLE HT_GIT_VERSION RETURN_VALUE GIT_RETURN)

if (GIT_RETURN STREQUAL "0")
  set(HT_VCS_STRING ${HT_GIT_VERSION})
else ()
  set(HT_VCS_STRING "exported")
endif ()

set(VERSION_STRING "Bee ${VERSION} (${HT_VCS_STRING})")
